### ISSUE TITLE
Add accelerometer sensor (3D) and collect information for it

### ISSUE THREAD

**Issue by usaguerrilla** [far-far-away-science/hab-v2#12]
save to SD 
send max acceleration to date over telemetry radio channel

**Comment by usaguerrilla** [comment]
assigned DMA to I2C.

https://github.com/far-far-away-science/hab-v2/wiki/dma_usage

**Comment by usaguerrilla** [comment]
See sensors list:
https://github.com/far-far-away-science/hab-v2/wiki/sensors_list

**Comment by stcarlso** [comment]
Implemented in Phoenix, accelerometer data is read and logged over serial port
