### ISSUE TITLE
Collect Battery and GPS chip temperature

### ISSUE THREAD

**Issue by usaguerrilla** [far-far-away-science/hab-v2#58]
These are simple analogue temperature sensors (see sensors list) read through MCU ADC ports.
No need to read them more than once in 1-5 minutes.
Save to telemetry / SD (once this functionality is finished).

**Comment by usaguerrilla** [comment]
See sensor list for more info
https://github.com/far-far-away-science/hab-v2/wiki/sensors_list

**Comment by stcarlso** [comment]
External DS18(B)20 sensors are implemented in Phoenix
